RA-25-recipe-count-in-view-model
i1qxa/StartAndroidApp pull request #21
Opened 2024-11-23 18:34 UTC by i1qxa

Вынес обработку количества порций в view model

2024-11-23 23:48 UTC, Churickoid requested changes

2024-11-23 23:48 UTC, Churickoid commented on app/src/main/java/aps/fithom/startandroidapp/ui/recipes/recipe/RecipeFragment.kt
>                  binding.rvCookingMethods.adapter = cookingMethodRVAdapter
Сейчас каждый раз при изменении стейта создается новый объект адаптера. Плодить много объектов -  не очень хорошая практика, всегда лучше использовать один. 
Давай прилинковывать адаптер к ресайклер вью только один раз вне observer. Внутри observer, по аналогии с количеством порций, добавить методе updateDataSet, где будет меняться переменная dataSet. Чтоб ресайклерВью понимал, что ему нужно отрисовать новый список, надо не забыть добавить - notifyDataSetChanged

2024-11-24 15:13 UTC, i1qxa commented
Привет, подскажи не проще ли использовать ListAdapter вместо RecyclerView.Adapter, чтобы не делать дополнительных манипуляций с данными для адаптера, а просто вызвать rvAdapter.submitList(data) внутри LiveData ?

2024-11-24 21:42 UTC, Churickoid approved these changes
Поправил верно, молодец! Курс построен с использованием RecyclerView.Adapter. Запрещать реализовывать на ListAdapter не буду, можешь перейти на них, оно попроще. Единственный минус - она под копотом свою анимацию странную тянет при изменении объектов адаптера, можешь поискать как её отключить

2024-11-25 17:21 UTC, merged